import { AbiItem } from "web3-utils";

export const DXDAO_ABI: AbiItem[] = [
  {
    constant: true,
    inputs: [],
    name: "orgName",
    outputs: [{ name: "", type: "string" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_contract", type: "address" },
      { name: "_data", type: "bytes" },
      { name: "_value", type: "uint256" },
    ],
    name: "genericCall",
    outputs: [
      { name: "success", type: "bool" },
      { name: "returnValue", type: "bytes" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "_metaData", type: "string" }],
    name: "metaData",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "nativeReputation",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isOwner",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_externalToken", type: "address" },
      { name: "_spender", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "externalTokenApproval",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_externalToken", type: "address" },
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "externalTokenTransferFrom",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_amountInWei", type: "uint256" },
      { name: "_to", type: "address" },
    ],
    name: "sendEther",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_externalToken", type: "address" },
      { name: "_to", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "externalTokenTransfer",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "nativeToken",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_orgName", type: "string" },
      { name: "_nativeToken", type: "address" },
      { name: "_nativeReputation", type: "address" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { payable: true, stateMutability: "payable", type: "fallback" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_contract", type: "address" },
      { indexed: false, name: "_data", type: "bytes" },
      { indexed: false, name: "_value", type: "uint256" },
      { indexed: false, name: "_success", type: "bool" },
    ],
    name: "GenericCall",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "_amountInWei", type: "uint256" },
      { indexed: true, name: "_to", type: "address" },
    ],
    name: "SendEther",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_externalToken", type: "address" },
      { indexed: true, name: "_to", type: "address" },
      { indexed: false, name: "_value", type: "uint256" },
    ],
    name: "ExternalTokenTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_externalToken", type: "address" },
      { indexed: false, name: "_from", type: "address" },
      { indexed: false, name: "_to", type: "address" },
      { indexed: false, name: "_value", type: "uint256" },
    ],
    name: "ExternalTokenTransferFrom",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_externalToken", type: "address" },
      { indexed: false, name: "_spender", type: "address" },
      { indexed: false, name: "_value", type: "uint256" },
    ],
    name: "ExternalTokenApproval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_sender", type: "address" },
      { indexed: false, name: "_value", type: "uint256" },
    ],
    name: "ReceiveEther",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "_metaData", type: "string" }],
    name: "MetaData",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];
export const LAO_ABI: AbiItem[] = [
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "applicant", type: "address" },
      { name: "proposer", type: "address" },
      { name: "sponsor", type: "address" },
      { name: "sharesRequested", type: "uint256" },
      { name: "lootRequested", type: "uint256" },
      { name: "tributeOffered", type: "uint256" },
      { name: "tributeToken", type: "address" },
      { name: "paymentRequested", type: "uint256" },
      { name: "paymentToken", type: "address" },
      { name: "startingPeriod", type: "uint256" },
      { name: "yesVotes", type: "uint256" },
      { name: "noVotes", type: "uint256" },
      { name: "details", type: "string" },
      { name: "maxTotalSharesAndLootAtYesVote", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "processingReward",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "memberAddress", type: "address" },
      { name: "proposalIndex", type: "uint256" },
    ],
    name: "getMemberProposalVote",
    outputs: [{ name: "", type: "uint8" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getCurrentPeriod",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "members",
    outputs: [
      { name: "delegateKey", type: "address" },
      { name: "shares", type: "uint256" },
      { name: "loot", type: "uint256" },
      { name: "exists", type: "bool" },
      { name: "highestIndexYesVote", type: "uint256" },
      { name: "jailed", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "withdrawBalance",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "memberToKick", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitGuildKickProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "sharesToBurn", type: "uint256" },
      { name: "lootToBurn", type: "uint256" },
    ],
    name: "ragequit",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "approvedTokens",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "newDelegateKey", type: "address" }],
    name: "updateDelegateKey",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "TOTAL",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processWhitelistProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalShares",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "proposalQueue",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "proposedToKick",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "memberAddressByDelegateKey",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "tokens", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "max", type: "bool" },
    ],
    name: "withdrawBalances",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    name: "userTokenBalances",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "applicant", type: "address" },
      { name: "sharesRequested", type: "uint256" },
      { name: "lootRequested", type: "uint256" },
      { name: "tributeOffered", type: "uint256" },
      { name: "tributeToken", type: "address" },
      { name: "paymentRequested", type: "uint256" },
      { name: "paymentToken", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "token", type: "address" }],
    name: "collectTokens",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalLoot",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "gracePeriodLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "user", type: "address" },
      { name: "token", type: "address" },
    ],
    name: "getUserTokenBalance",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "tokenWhitelist",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getTokenCount",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getProposalQueueLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "summoningTime",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "votingPeriodLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalDeposit",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isOwner",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "startingPeriod", type: "uint256" }],
    name: "hasVotingPeriodExpired",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "sponsorProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "proposalIndex", type: "uint256" },
      { name: "uintVote", type: "uint8" },
    ],
    name: "submitVote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalGuildBankTokens",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "highestIndexYesVote", type: "uint256" }],
    name: "canRagequit",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "dilutionBound",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "getProposalFlags",
    outputs: [{ name: "", type: "bool[6]" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "periodDuration",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_adminFeeDenominator", type: "uint256" },
      { name: "_laoFundAddress", type: "address" },
    ],
    name: "setAdminFee",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "depositToken",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "laoFundAddress",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalCount",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "memberToKick", type: "address" }],
    name: "ragekick",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "lastPaymentTime",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "cancelProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "proposedToWhitelist",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processGuildKickProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ESCROW",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "GUILD",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "adminFeeDenominator",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "withdrawAdminFee",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "tokenToWhitelist", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitWhitelistProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_summoner", type: "address" },
      { name: "_approvedTokens", type: "address[]" },
      { name: "_periodDuration", type: "uint256" },
      { name: "_votingPeriodLength", type: "uint256" },
      { name: "_gracePeriodLength", type: "uint256" },
      { name: "_proposalDeposit", type: "uint256" },
      { name: "_dilutionBound", type: "uint256" },
      { name: "_processingReward", type: "uint256" },
      { name: "_laoFundAddress", type: "address" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "summoner", type: "address" },
      { indexed: false, name: "tokens", type: "address[]" },
      { indexed: false, name: "summoningTime", type: "uint256" },
      { indexed: false, name: "periodDuration", type: "uint256" },
      { indexed: false, name: "votingPeriodLength", type: "uint256" },
      { indexed: false, name: "gracePeriodLength", type: "uint256" },
      { indexed: false, name: "proposalDeposit", type: "uint256" },
      { indexed: false, name: "dilutionBound", type: "uint256" },
      { indexed: false, name: "processingReward", type: "uint256" },
    ],
    name: "SummonComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "applicant", type: "address" },
      { indexed: false, name: "sharesRequested", type: "uint256" },
      { indexed: false, name: "lootRequested", type: "uint256" },
      { indexed: false, name: "tributeOffered", type: "uint256" },
      { indexed: false, name: "tributeToken", type: "address" },
      { indexed: false, name: "paymentRequested", type: "uint256" },
      { indexed: false, name: "paymentToken", type: "address" },
      { indexed: false, name: "details", type: "string" },
      { indexed: false, name: "flags", type: "bool[6]" },
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
    ],
    name: "SubmitProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: false, name: "proposalIndex", type: "uint256" },
      { indexed: false, name: "startingPeriod", type: "uint256" },
    ],
    name: "SponsorProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "uintVote", type: "uint8" },
    ],
    name: "SubmitVote",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessWhitelistProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessGuildKickProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "sharesToBurn", type: "uint256" },
      { indexed: false, name: "lootToBurn", type: "uint256" },
    ],
    name: "Ragequit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amountToCollect", type: "uint256" },
    ],
    name: "TokensCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "applicantAddress", type: "address" },
    ],
    name: "CancelProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "newDelegateKey", type: "address" },
    ],
    name: "UpdateDelegateKey",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];

export const MOLOCH_ABI: AbiItem[] = [
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "applicant", type: "address" },
      { name: "proposer", type: "address" },
      { name: "sponsor", type: "address" },
      { name: "sharesRequested", type: "uint256" },
      { name: "lootRequested", type: "uint256" },
      { name: "tributeOffered", type: "uint256" },
      { name: "tributeToken", type: "address" },
      { name: "paymentRequested", type: "uint256" },
      { name: "paymentToken", type: "address" },
      { name: "startingPeriod", type: "uint256" },
      { name: "yesVotes", type: "uint256" },
      { name: "noVotes", type: "uint256" },
      { name: "details", type: "string" },
      { name: "maxTotalSharesAndLootAtYesVote", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "processingReward",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "memberAddress", type: "address" },
      { name: "proposalIndex", type: "uint256" },
    ],
    name: "getMemberProposalVote",
    outputs: [{ name: "", type: "uint8" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getCurrentPeriod",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "members",
    outputs: [
      { name: "delegateKey", type: "address" },
      { name: "shares", type: "uint256" },
      { name: "loot", type: "uint256" },
      { name: "exists", type: "bool" },
      { name: "highestIndexYesVote", type: "uint256" },
      { name: "jailed", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "withdrawBalance",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "memberToKick", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitGuildKickProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "sharesToBurn", type: "uint256" },
      { name: "lootToBurn", type: "uint256" },
    ],
    name: "ragequit",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "approvedTokens",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "newDelegateKey", type: "address" }],
    name: "updateDelegateKey",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "TOTAL",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processWhitelistProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalShares",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "proposalQueue",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "proposedToKick",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "memberAddressByDelegateKey",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "tokens", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "max", type: "bool" },
    ],
    name: "withdrawBalances",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    name: "userTokenBalances",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "applicant", type: "address" },
      { name: "sharesRequested", type: "uint256" },
      { name: "lootRequested", type: "uint256" },
      { name: "tributeOffered", type: "uint256" },
      { name: "tributeToken", type: "address" },
      { name: "paymentRequested", type: "uint256" },
      { name: "paymentToken", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "token", type: "address" }],
    name: "collectTokens",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalLoot",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "gracePeriodLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "user", type: "address" },
      { name: "token", type: "address" },
    ],
    name: "getUserTokenBalance",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "tokenWhitelist",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getTokenCount",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getProposalQueueLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "summoningTime",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "votingPeriodLength",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalDeposit",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "startingPeriod", type: "uint256" }],
    name: "hasVotingPeriodExpired",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "sponsorProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "proposalIndex", type: "uint256" },
      { name: "uintVote", type: "uint8" },
    ],
    name: "submitVote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalGuildBankTokens",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "highestIndexYesVote", type: "uint256" }],
    name: "canRagequit",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_summoner", type: "address[]" },
      { name: "_approvedTokens", type: "address[]" },
      { name: "_periodDuration", type: "uint256" },
      { name: "_votingPeriodLength", type: "uint256" },
      { name: "_gracePeriodLength", type: "uint256" },
      { name: "_proposalDeposit", type: "uint256" },
      { name: "_dilutionBound", type: "uint256" },
      { name: "_processingReward", type: "uint256" },
      { name: "_summonerShares", type: "uint256[]" },
    ],
    name: "init",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "dilutionBound",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "getProposalFlags",
    outputs: [{ name: "", type: "bool[6]" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "memberList",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "periodDuration",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "depositToken",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalCount",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "memberToKick", type: "address" }],
    name: "ragekick",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "cancelProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "proposedToWhitelist",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processGuildKickProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "proposalIndex", type: "uint256" }],
    name: "processProposal",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ESCROW",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "GUILD",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "tokenToWhitelist", type: "address" },
      { name: "details", type: "string" },
    ],
    name: "submitWhitelistProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "summoner", type: "address" },
      { indexed: false, name: "tokens", type: "address[]" },
      { indexed: false, name: "summoningTime", type: "uint256" },
      { indexed: false, name: "periodDuration", type: "uint256" },
      { indexed: false, name: "votingPeriodLength", type: "uint256" },
      { indexed: false, name: "gracePeriodLength", type: "uint256" },
      { indexed: false, name: "proposalDeposit", type: "uint256" },
      { indexed: false, name: "dilutionBound", type: "uint256" },
      { indexed: false, name: "processingReward", type: "uint256" },
    ],
    name: "SummonComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "applicant", type: "address" },
      { indexed: false, name: "sharesRequested", type: "uint256" },
      { indexed: false, name: "lootRequested", type: "uint256" },
      { indexed: false, name: "tributeOffered", type: "uint256" },
      { indexed: false, name: "tributeToken", type: "address" },
      { indexed: false, name: "paymentRequested", type: "uint256" },
      { indexed: false, name: "paymentToken", type: "address" },
      { indexed: false, name: "details", type: "string" },
      { indexed: false, name: "flags", type: "bool[6]" },
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
    ],
    name: "SubmitProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: false, name: "proposalIndex", type: "uint256" },
      { indexed: false, name: "startingPeriod", type: "uint256" },
    ],
    name: "SponsorProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "proposalId", type: "uint256" },
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "delegateKey", type: "address" },
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "uintVote", type: "uint8" },
    ],
    name: "SubmitVote",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessWhitelistProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalIndex", type: "uint256" },
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "didPass", type: "bool" },
    ],
    name: "ProcessGuildKickProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "sharesToBurn", type: "uint256" },
      { indexed: false, name: "lootToBurn", type: "uint256" },
    ],
    name: "Ragequit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amountToCollect", type: "uint256" },
    ],
    name: "TokensCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: false, name: "applicantAddress", type: "address" },
    ],
    name: "CancelProposal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "newDelegateKey", type: "address" },
    ],
    name: "UpdateDelegateKey",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "memberAddress", type: "address" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
];

export const DXREP_ABI: AbiItem[] = [
  {
    constant: true,
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_user", type: "address" },
      { name: "_amount", type: "uint256" },
    ],
    name: "mint",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "_owner", type: "address" },
      { name: "_blockNumber", type: "uint256" },
    ],
    name: "balanceOfAt",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "_owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "balance", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isOwner",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "_blockNumber", type: "uint256" }],
    name: "totalSupplyAt",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_user", type: "address" },
      { name: "_amount", type: "uint256" },
    ],
    name: "burn",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_to", type: "address" },
      { indexed: false, name: "_amount", type: "uint256" },
    ],
    name: "Mint",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_from", type: "address" },
      { indexed: false, name: "_amount", type: "uint256" },
    ],
    name: "Burn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];

export const CURVE_ABI: AbiItem[] = [
  {
    name: "CommitOwnership",
    inputs: [{ type: "address", name: "admin", indexed: false }],
    anonymous: false,
    type: "event",
  },
  {
    name: "ApplyOwnership",
    inputs: [{ type: "address", name: "admin", indexed: false }],
    anonymous: false,
    type: "event",
  },
  {
    name: "Deposit",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256", name: "value", indexed: false },
      { type: "uint256", name: "locktime", indexed: true },
      { type: "int128", name: "type", indexed: false },
      { type: "uint256", name: "ts", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "Withdraw",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256", name: "value", indexed: false },
      { type: "uint256", name: "ts", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "Supply",
    inputs: [
      { type: "uint256", name: "prevSupply", indexed: false },
      { type: "uint256", name: "supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    outputs: [],
    inputs: [
      { type: "address", name: "token_addr" },
      { type: "string", name: "_name" },
      { type: "string", name: "_symbol" },
      { type: "string", name: "_version" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    name: "commit_transfer_ownership",
    outputs: [],
    inputs: [{ type: "address", name: "addr" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 37597,
  },
  {
    name: "apply_transfer_ownership",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 38497,
  },
  {
    name: "commit_smart_wallet_checker",
    outputs: [],
    inputs: [{ type: "address", name: "addr" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 36307,
  },
  {
    name: "apply_smart_wallet_checker",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 37095,
  },
  {
    name: "get_last_user_slope",
    outputs: [{ type: "int128", name: "" }],
    inputs: [{ type: "address", name: "addr" }],
    stateMutability: "view",
    type: "function",
    gas: 2569,
  },
  {
    name: "user_point_history__ts",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "address", name: "_addr" },
      { type: "uint256", name: "_idx" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 1672,
  },
  {
    name: "locked__end",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "address", name: "_addr" }],
    stateMutability: "view",
    type: "function",
    gas: 1593,
  },
  {
    name: "checkpoint",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 37052342,
  },
  {
    name: "deposit_for",
    outputs: [],
    inputs: [
      { type: "address", name: "_addr" },
      { type: "uint256", name: "_value" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74279891,
  },
  {
    name: "create_lock",
    outputs: [],
    inputs: [
      { type: "uint256", name: "_value" },
      { type: "uint256", name: "_unlock_time" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74281465,
  },
  {
    name: "increase_amount",
    outputs: [],
    inputs: [{ type: "uint256", name: "_value" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74280830,
  },
  {
    name: "increase_unlock_time",
    outputs: [],
    inputs: [{ type: "uint256", name: "_unlock_time" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74281578,
  },
  {
    name: "withdraw",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 37223566,
  },
  {
    name: "balanceOf",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "address", name: "addr" }],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "balanceOf",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "address", name: "addr" },
      { type: "uint256", name: "_t" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "balanceOfAt",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "address", name: "addr" },
      { type: "uint256", name: "_block" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 514333,
  },
  {
    name: "totalSupply",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "totalSupply",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "t" }],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "totalSupplyAt",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "_block" }],
    stateMutability: "view",
    type: "function",
    gas: 812560,
  },
  {
    name: "changeController",
    outputs: [],
    inputs: [{ type: "address", name: "_newController" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 36907,
  },
  {
    name: "token",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 1841,
  },
  {
    name: "supply",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 1871,
  },
  {
    name: "locked",
    outputs: [
      { type: "int128", name: "amount" },
      { type: "uint256", name: "end" },
    ],
    inputs: [{ type: "address", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 3359,
  },
  {
    name: "epoch",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 1931,
  },
  {
    name: "point_history",
    outputs: [
      { type: "int128", name: "bias" },
      { type: "int128", name: "slope" },
      { type: "uint256", name: "ts" },
      { type: "uint256", name: "blk" },
    ],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 5550,
  },
  {
    name: "user_point_history",
    outputs: [
      { type: "int128", name: "bias" },
      { type: "int128", name: "slope" },
      { type: "uint256", name: "ts" },
      { type: "uint256", name: "blk" },
    ],
    inputs: [
      { type: "address", name: "arg0" },
      { type: "uint256", name: "arg1" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 6079,
  },
  {
    name: "user_point_epoch",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "address", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2175,
  },
  {
    name: "slope_changes",
    outputs: [{ type: "int128", name: "" }],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2166,
  },
  {
    name: "controller",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2081,
  },
  {
    name: "transfersEnabled",
    outputs: [{ type: "bool", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2111,
  },
  {
    name: "name",
    outputs: [{ type: "string", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 8543,
  },
  {
    name: "symbol",
    outputs: [{ type: "string", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 7596,
  },
  {
    name: "version",
    outputs: [{ type: "string", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 7626,
  },
  {
    name: "decimals",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2231,
  },
  {
    name: "future_smart_wallet_checker",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2261,
  },
  {
    name: "smart_wallet_checker",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2291,
  },
  {
    name: "admin",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2321,
  },
  {
    name: "future_admin",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2351,
  },
];

export const MAKER_CHIEF: AbiItem[] = [
  {
    inputs: [
      { internalType: "contract DSToken", name: "GOV", type: "address" },
      { internalType: "contract DSToken", name: "IOU", type: "address" },
      { internalType: "uint256", name: "MAX_YAYS", type: "uint256" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "slate",
        type: "bytes32",
      },
    ],
    name: "Etch",
    type: "event",
  },
  {
    anonymous: true,
    inputs: [
      { indexed: true, internalType: "bytes4", name: "sig", type: "bytes4" },
      { indexed: true, internalType: "address", name: "guy", type: "address" },
      { indexed: true, internalType: "bytes32", name: "foo", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "bar", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "wad", type: "uint256" },
      { indexed: false, internalType: "bytes", name: "fax", type: "bytes" },
    ],
    name: "LogNote",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "LogSetAuthority",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "LogSetOwner",
    type: "event",
  },
  {
    constant: true,
    inputs: [],
    name: "GOV",
    outputs: [{ internalType: "contract DSToken", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "IOU",
    outputs: [{ internalType: "contract DSToken", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "MAX_YAYS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "approvals",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "authority",
    outputs: [
      { internalType: "contract DSAuthority", name: "", type: "address" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "address", name: "caller", type: "address" },
      { internalType: "address", name: "code", type: "address" },
      { internalType: "bytes4", name: "sig", type: "bytes4" },
    ],
    name: "canCall",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "deposits",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address[]", name: "yays", type: "address[]" }],
    name: "etch",
    outputs: [{ internalType: "bytes32", name: "slate", type: "bytes32" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "wad", type: "uint256" }],
    name: "free",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "address", name: "code", type: "address" },
      { internalType: "bytes4", name: "sig", type: "bytes4" },
    ],
    name: "getCapabilityRoles",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "who", type: "address" }],
    name: "getUserRoles",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "address", name: "who", type: "address" },
      { internalType: "uint8", name: "role", type: "uint8" },
    ],
    name: "hasUserRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "hat",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "address", name: "code", type: "address" },
      { internalType: "bytes4", name: "sig", type: "bytes4" },
    ],
    name: "isCapabilityPublic",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "who", type: "address" }],
    name: "isUserRoot",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "last",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "launch",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "whom", type: "address" }],
    name: "lift",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "live",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "wad", type: "uint256" }],
    name: "lock",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "contract DSAuthority",
        name: "authority_",
        type: "address",
      },
    ],
    name: "setAuthority",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "owner_", type: "address" }],
    name: "setOwner",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "code", type: "address" },
      { internalType: "bytes4", name: "sig", type: "bytes4" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setPublicCapability",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "uint8", name: "role", type: "uint8" },
      { internalType: "address", name: "code", type: "address" },
      { internalType: "bytes4", name: "sig", type: "bytes4" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setRoleCapability",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "who", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setRootUser",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "who", type: "address" },
      { internalType: "uint8", name: "role", type: "uint8" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "setUserRole",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "slates",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "bytes32", name: "slate", type: "bytes32" }],
    name: "vote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address[]", name: "yays", type: "address[]" }],
    name: "vote",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "votes",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
